// Generated by Wrangler on Thu May 09 2024 23:33:30 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
  CLIENT_SECRET: string;
  CLIENT_ID: string;
  AUTH_SECRET: string;
  DB: D1Database;
}
