name = "zaraz-app"
pages_build_output_dir = "./build/client"
compatibility_date = "2024-05-12"

[vars]
VERSION = "local"

[[d1_databases]]
binding = "DB"
database_name = "d1-zaraz-app"
database_id = "99b6c6c6-c0da-4f39-bd15-dfb5d4bac66a"
migrations_dir = "./migrations"
